=== oneliang/builder-java/src/test/resources/config/builder.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT builder (configuration-class,configuration*,handler*,task-node-insert*)>
<!ELEMENT configuration-class EMPTY>
<!ATTLIST configuration-class type CDATA #REQUIRED>
<!ELEMENT configuration EMPTY>
<!ATTLIST configuration name CDATA #REQUIRED>
<!ATTLIST configuration value CDATA #REQUIRED>
<!ATTLIST configuration log (true|false) #IMPLIED>
<!ELEMENT handler (reference-handler-name*,command*)>
<!ATTLIST handler name CDATA #REQUIRED>
<!ATTLIST handler type CDATA #REQUIRED>
<!ATTLIST handler mode (singleton|more) #IMPLIED>
<!ATTLIST handler inputKeyValue CDATA #IMPLIED>
<!ATTLIST handler outputKey CDATA #IMPLIED>
<!ELEMENT reference-handler-name EMPTY>
<!ATTLIST reference-handler-name value CDATA #REQUIRED>
<!ELEMENT command EMPTY>
<!ATTLIST command value CDATA #REQUIRED>
<!ELEMENT task-node-insert (parent-name*,handler-name*)>
<!ATTLIST task-node-insert name CDATA #REQUIRED>
<!ATTLIST task-node-insert skip (false|true) #IMPLIED>
<!ELEMENT parent-name EMPTY>
<!ELEMENT handler-name EMPTY>
<!ATTLIST parent-name value CDATA #REQUIRED>
<!ATTLIST handler-name value CDATA #REQUIRED>

=== oneliang/builder-java/src/test/resources/config/java-builder.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE builder SYSTEM "builder.dtd">
<builder>
	<configuration-class type="com.oneliang.tools.builder.java.base.JavaConfigurationForEclipse"/>
	<configuration name="projectWorkspace" value="/D:/Dandelion/java/gitWorkspace"/>
	<configuration name="projectMain" value="builder"/>
	<configuration name="buildOutput" value="./builder-gen"/>
	<configuration name="jarKeystore" value="/D:/Dandelion/tencent/key/debug.keystore" log="false"/>
	<configuration name="jarStorePassword" value="android" log="false"/>
	<configuration name="jarKeyPassword" value="android" log="false"/>
	<configuration name="jarKeyAlias" value="androiddebugkey" log="false"/>
	<configuration name="projectTaskNodeInsertName" value="buildJavaProject"/>

	<handler name="clean" type="com.oneliang.tools.builder.java.handler.CleanHandler"/>
	<handler name="compileJavaProject" type="com.oneliang.tools.builder.java.handler.CompileJavaProjectHandler" mode="more"/>
	<handler name="buildJavaProject" type="com.oneliang.tools.builder.java.handler.JavaProjectHandler" mode="more">
		<reference-handler-name value="compileJavaProject"/>
	</handler>
	<handler name="generateJar" type="com.oneliang.tools.builder.java.handler.GenerateJarHandler"/>

	<task-node-insert name="clean">
		<handler-name value="clean"/>
	</task-node-insert>

	<task-node-insert name="buildJavaProject">
		<handler-name value="buildJavaProject"/>
	</task-node-insert>

	<task-node-insert name="generateJar">
		<parent-name value="buildJavaProject"/>
		<handler-name value="generateJar"/>
	</task-node-insert>
</builder>
